language: ruby
sudo: false
addons:
  apt:
    packages:
    - libcairo2-dev
    - make
install:
  - "source ./testsuite/install_dependencies.sh"
script: "cd testsuite; env -i PATH=$PATH:`pwd`/../_gt/bin ./testsuite.rb"
